version: "3.8"

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "${PORT}:${PORT}"  # Use the PORT variable from the .env file
    environment:
      - PORT=${PORT}  # Use the PORT variable from the .env file
    env_file:
      - .env  # Load environment variables from the .env file

    # If your app depends on a database, you can define that service here as well
    # Example:
    # depends_on:
    #   - db

    networks:
      - app-network

  # Example: You can add other services here, e.g., a database
  # db:
  #   image: postgres
  #   environment:
  #     - POSTGRES_USER=example
  #     - POSTGRES_PASSWORD=example
  #     - POSTGRES_DB=example_db
  #   networks:
  #     - app-network

networks:
  app-network:
    driver: bridge
